### PR TITLE
Support for dynamic exclude regex values 

### PR DESCRIPTION
**Pull request by hankjacobs**
Add ability to specify exclude regexes via config file. Monitor config file for changes and reload exclude regexes when changes are detected.

### CODE REVIEW

**Review by bkeroackdsc — COMMENTED** [review]
Is there any way to add tests? At least for your modified functionality?

**Comment by hankjacobs** [comment]
Only with significant effort. Fluentd only provides testing frameworks for input and output plugins (this one is a filter plugin). It comes down to whether it's worth the time or not. I'd make the case for it not being worth it since the majority of the code would remain untested.

**Comment by bkeroackdsc** [comment]
OK.

**Review by bkeroackdsc — APPROVED** [review]
LGTM

**Review by bkeroackdsc — APPROVED** [review]

**Pull request merged**
